[package]
name = "ingress-rpc-bin"
version.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[[bin]]
name = "ingress-rpc"
path = "src/main.rs"


[dependencies]
utils.workspace = true
base-bundles.workspace = true
audit.workspace = true
ingress-rpc.workspace = true
clap.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true
dotenvy.workspace = true
rdkafka.workspace = true
jsonrpsee.workspace = true
op-alloy-network.workspace = true
alloy-provider.workspace = true
