

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
homepage = "https://github.com/base/infra"
repository = "https://github.com/base/infra"
exclude = [".github/"]

[workspace]
resolver = "2"
members = ["crates/*", "bin/*"]
default-members = ["bin/*"]
exclude = [".github/"]

[workspace.lints.rust]
missing-debug-implementations = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"
unnameable-types = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
missing-const-for-fn = "warn"
redundant-clone = "warn"
clone-on-ref-ptr = "warn"
unnecessary-to-owned = "warn"
cloned-instead-of-copied = "warn"
flat-map-option = "warn"
implicit-clone = "warn"
or-fun-call = "warn"
use-self = "warn"
option-if-let-else = "warn"
uninlined-format-args = "warn"
manual-string-new = "warn"
single-char-pattern = "warn"
redundant-else = "warn"
match-same-arms = "warn"
undocumented-unsafe-blocks = "warn"
doc-markdown = "warn"
dbg-macro = "warn"
branches-sharing-code = "warn"
derive-partial-eq-without-eq = "warn"
explicit-into-iter-loop = "warn"
explicit-iter-loop = "warn"
iter-with-drain = "warn"
needless-pass-by-ref-mut = "warn"
string-lit-as-bytes = "warn"

[workspace.dependencies]
# Internal crates
audit = { path = "crates/audit" }
basectl-cli = { path = "crates/basectl" }
mempool-rebroadcaster = { path = "crates/mempool-rebroadcaster" }
sidecrush = { path = "crates/sidecrush" }
utils = { path = "crates/utils" }

# base-reth
base-bundles = { git = "https://github.com/base/base", branch = "main" }
base-flashtypes = { git = "https://github.com/base/base.git" }
base-reth-rpc-types = { git = "https://github.com/base/base", branch = "main" }

# revm
op-revm = { version = "15.0.0", default-features = false }
revm-context-interface = { version = "15.0.0", default-features = false }

# alloy
alloy-serde = { version = "1.0.41", default-features = false }
alloy-signer = { version = "1.0.41", default-features = false }
alloy-network = { version = "1.0.41", default-features = false }
alloy-provider = { version = "1.0.41", default-features = false }
alloy-consensus = { version = "1.0.41", default-features = false }
alloy-rpc-types = { version = "1.1.2", default-features = false }
alloy-primitives = { version = "1.4.1", default-features = false }
alloy-signer-local = { version = "1.0.41", default-features = false }
alloy-genesis = { version = "1.0.41", default-features = false }
alloy-eips = { version = "1.0.41", default-features = false }
alloy-rpc-types-engine = { version = "1.0.41", default-features = false }
alloy-rpc-types-eth = { version = "1.0.41" }
alloy-trie = { version = "0.9.1", default-features = false }
alloy-hardforks = { version = "0.5" }
alloy-rpc-client = { version = "1.5.2" }
alloy-transport-http = { version = "1.5.2" }
alloy-sol-types = { version = "1.5.2" }
alloy-contract = { version = "1.5.2" }

# op-alloy
op-alloy-flz = { version = "0.13.1", default-features = false }
op-alloy-network = { version = "0.22.0", default-features = false }
op-alloy-rpc-types = { version = "0.22.0", default-features = false }
op-alloy-consensus = { version = "0.22.0", default-features = false }
op-alloy-rpc-types-engine = { version = "0.22.0", default-features = false }

# tokio
tokio = { version = "1.47.1", features = ["full"] }

# async
async-trait = "0.1.89"
futures = { version = "0.3.31", default-features = false }
futures-util = "0.3"

# rpc
jsonrpsee = { version = "0.26.0", default-features = false }

# kafka and s3
bytes = { version = "1.8.0", default-features = false }
rdkafka = { version = "0.37.0", default-features = false }
aws-config = { version = "1.1.7", default-features = false }
aws-sdk-s3 = { version = "1.106.0", default-features = false }
aws-credential-types = { version = "1.1.7", default-features = false }

# misc
tokio-tungstenite = { version = "0.26", features = ["native-tls"] }
url = { version = "2.5.7", default-features = false }
axum = { version = "0.8.3", default-features = false }
ratatui = "0.29"
crossterm = "0.28"
clap = { version = "4.5.47", default-features = false, features = ["std", "derive", "env"] }
chrono = "0.4"
anyhow = { version = "1.0.99", default-features = false }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.143", default-features = false }
serde_yaml = "0.9"
uuid = { version = "1.18.1", default-features = false }
backon = { version = "1.5.2", default-features = false }
dirs = "6.0"
arboard = "3.4"
dotenvy = { version = "0.15.7", default-features = false }
tracing = { version = "0.1.41", default-features = false }
tracing-subscriber = { version = "0.3.20", default-features = false, features = ["env-filter", "fmt", "ansi", "json"] }
wiremock = { version = "0.6.2", default-features = false }
metrics = { version = "0.24.1", default-features = false }
metrics-derive = { version = "0.1", default-features = false }
metrics-exporter-prometheus = { version = "0.17.0", default-features = false }
testcontainers = { version = "0.23.1", default-features = false }
testcontainers-modules = { version = "0.11.2", default-features = false }
moka = { version = "0.12.12", default-features = false }
cadence = "1.4"
