[workspace]
resolver = "2"
members = ["crates/mempool-rebroadcaster", "crates/sidecrush", "crates/gobrr", "bin/gobrr"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.lints.rust]
missing-debug-implementations = "warn"
unreachable-pub = "warn"
unused-must-use = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[workspace.dependencies]
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt", "ansi", "json"] }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
metrics = "0.24.1"
metrics-derive = "0.1"
cadence = "1.4"
cadence-macros = "1.4"
axum = "0.8"
tower-http = { version = "0.6", features = ["trace"] }
anyhow = "1.0"
url = "2.5"
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json"] }
dotenvy = "0.15.7"
async-trait = "0.1"

# alloy
alloy-primitives = { version = "1.0", default-features = false, features = [
    "map-foldhash",
    "serde",
] }
alloy-genesis = { version = "1.0", default-features = false }
alloy-eips = { version = "1.0", default-features = false }
alloy-rpc-types = { version = "1.0", default-features = false }
alloy-rpc-types-engine = { version = "1.0", default-features = false }
alloy-rpc-types-eth = { version = "1.0" }
alloy-consensus = { version = "1.0" }
alloy-trie = { version = "0.9", default-features = false }
alloy-provider = { version = "1.0" }
alloy-hardforks = { version = "0.4" }
alloy-rpc-client = { version = "1.0" }
alloy-transport-http = { version = "1.0" }
alloy-signer = { version = "1.0" }
alloy-signer-local = { version = "1.0", features = ["mnemonic"] }
alloy-network = { version = "1.0" }

# op-alloy
op-alloy-rpc-types = { version = "0.22.0", default-features = false }
op-alloy-rpc-types-engine = { version = "0.22.0", default-features = false }
op-alloy-rpc-jsonrpsee = { version = "0.22.0", default-features = false }
op-alloy-consensus = { version = "0.22.0", default-features = false }
op-alloy-network = { version = "0.22.0" }

# internal
gobrr = { path = "crates/gobrr" }
