verbose = "debug"
no_progress = false
exclude_all_private = false
accept = [200, 403]
exclude = [
    'localhost',
    'foo.bar',
    'https://img.shields.io/github/commit-activity/w/refcell/roxy',
    'https://img.shields.io/github/issues-pr-raw/refcell/roxy',
]
