[package]
name = "roxy"
description = "High-performance Ethereum JSON-RPC proxy"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# internal
roxy-config.workspace = true
roxy-server.workspace = true
roxy-backend.workspace = true
roxy-runtime.workspace = true

# async
tokio.workspace = true

# cli
clap = { version = "4.5", features = ["derive"] }

# logging
tracing.workspace = true
tracing-subscriber.workspace = true

# error handling
eyre.workspace = true

[features]
default = []
